CREATE DATABASE GEOGRAPHIC_REGISTRY;
USE GEOGRAPHIC_REGISTRY;

CREATE TABLE STATES(
	ID BIGINT AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CAPITAL VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MUNICIPALITIES(
	ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    STATES_ID BIGINT NOT NULL,
    CONSTRAINT FK_MUNICIPALITIES_STATES
		FOREIGN KEY (STATES_ID)
		REFERENCES STATES(ID),
	PRIMARY KEY(ID)
);

CREATE TABLE LOCALITIES(
	ID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
    POPULATION_TYPE VARCHAR (10) NOT NULL,
    SETTLEMENT_TYPE VARCHAR (30) NOT NULL,
	POSTAL_CODE VARCHAR(10) NOT NULL,
    MUNICIPALITIES_ID BIGINT NOT NULL,
    CONSTRAINT FK_LOCALITIES_MUNICIPALITIES
		FOREIGN KEY (MUNICIPALITIES_ID)
        REFERENCES MUNICIPALITIES(ID),
	PRIMARY KEY(ID)
);
