CREATE DATABASE GEOGRAPHIC_REGISTRY;
USE GEOGRAPHIC_REGISTRY;

CREATE TABLE STATE(
	STATE_ID INT AUTO_INCREMENT NOT NULL,
	STATE_NAME VARCHAR(50) NOT NULL,
	STATE_CAPITAL VARCHAR(50) NOT NULL,
    PRIMARY KEY (STATE_ID)
);

CREATE TABLE MUNICIPALITY(
	MUNICIPALITY_ID INT AUTO_INCREMENT,
    MUNICIPALITY_NAME VARCHAR(50) NOT NULL,
    STATE_ID INT NOT NULL,
    CONSTRAINT FK_MUNICIPALITY_STATE
		FOREIGN KEY (STATE_ID)
		REFERENCES STATE(STATE_ID),
	PRIMARY KEY(MUNICIPALITY_ID)
);

CREATE TABLE LOCALITY(
	LOCALITY_ID INT AUTO_INCREMENT,
	LOCALITY_NAME VARCHAR(100) NOT NULL,
    POPULATION_TYPE VARCHAR (10) NOT NULL,
    SETTLEMENT_TYPE VARCHAR (30) NOT NULL,
	POSTAL_CODE VARCHAR(10) NOT NULL,
    MUNICIPALITY_ID INT NOT NULL,
    CONSTRAINT FK_LOCALITY_MUNICIPALITY
		FOREIGN KEY (MUNICIPALITY_ID)
        REFERENCES MUNICIPALITY(MUNICIPALITY_ID),
	PRIMARY KEY(LOCALITY_ID)
);
select * from state;

